find_package(Python 3.6 REQUIRED COMPONENTS Interpreter Development.Module NumPy)
if (Python_FOUND)
    message(STATUS "${Green}Python ver. ${Python_VERSION} found.${ColourReset}")
    get_target_property(Python_LIBDIR Python::Python LOCATION)
    get_filename_component(Python_LIBDIR ${Python_LIBDIR} DIRECTORY)
    message(STATUS "${Green}Python library directory: Python_LIBDIR=${Python_LIBDIR} ${ColourReset}")
    set(HEPPY_PYTHON_FOUND True)
  else(Python_FOUND)
    message(FATAL_ERROR "${Red}Python not found while it is the key package here...${ColourReset}")
endif(Python_FOUND)
