# - Find CGAL
# Find the FASTJET includes and client library
# This module defines
#  FASTJET_INCLUDE_DIR, where to find PseudoJet.hh
#  FASTJET_LIBRARIES, the libraries needed to use CGAL.
#  FASTJET_FOUND, If false, do not try to use CGAL.

if (NOT FASTJET_DIR)
  find_program ( FASTJETCONFIG fastjet-config PATHS $ENV{FASTJET_DIR}/bin ${FASTJET_DIR}/bin)
  if (NOT EXISTS ${FASTJETCONFIG})
    message(STATUS "Setting FASTJET_DIR to ${FASTJET_DIR}")
  endif(NOT EXISTS ${FASTJETCONFIG})
endif(NOT FASTJET_DIR)

if(FASTJET_INCLUDE_DIR AND FASTJET_LIBRARIES)
   set(FASTJET_FOUND TRUE)
else(FASTJET_INCLUDE_DIR AND FASTJET_LIBRARIES)
  message(STATUS "Looking for FastJet with fastjet-config...")
  find_program ( FASTJETCONFIG fastjet-config PATHS $ENV{FASTJET_DIR}/bin ${FASTJET_DIR}/bin)
  if (EXISTS ${FASTJETCONFIG})
    message(STATUS "Using fastjet-config at ${FASTJETCONFIG}")
    execute_process ( COMMAND ${FASTJETCONFIG} --prefix WORKING_DIRECTORY /tmp OUTPUT_VARIABLE FASTJET_DIR OUTPUT_STRIP_TRAILING_WHITESPACE )
    execute_process ( COMMAND ${FASTJETCONFIG} --cxxflags WORKING_DIRECTORY /tmp OUTPUT_VARIABLE FASTJET_CXXFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE )
    execute_process ( COMMAND ${FASTJETCONFIG} --libs --plugins WORKING_DIRECTORY /tmp OUTPUT_VARIABLE FASTJET_LIBS OUTPUT_STRIP_TRAILING_WHITESPACE )
    execute_process ( COMMAND ${FASTJETCONFIG} --version WORKING_DIRECTORY /tmp OUTPUT_VARIABLE FASTJET_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE )
    set(FASTJET_LIBRARIES ${FASTJET_LIBS})
    set(FASTJET_INCLUDE_DIR ${FASTJET_CXXFLAGS})
    set(FASTJET_FOUND TRUE)
  else(EXISTS ${FASTJETCONFIG})
    message(STATUS "${Yellow}Hint: fastjet-config not in \$PATH nor in \${FASTJET_DIR}/bin${ColourReset}")
  endif()
  mark_as_advanced(FASTJET_INCLUDE_DIR FASTJET_LIBRARIES FASTJET_DIR)
endif(FASTJET_INCLUDE_DIR AND FASTJET_LIBRARIES)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FastJet DEFAULT_MSG FASTJET_DIR FASTJET_INCLUDE_DIR FASTJET_LIBRARIES)

if(FASTJET_FOUND)
  message(STATUS "${Green}FASTJET ver. ${FASTJET_VERSION}${ColourReset}")
endif(FASTJET_FOUND)
